modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
    modId = "rottencreatures"
    version = "${version}"
    displayName = "Rotten Creatures"
    authors = "Team Fusion"
    description = '''
    This is an example description! Tell everyone what your mod is about!
    '''
    logoFile = "icon.png"

[[dependencies.rottencreatures]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.rottencreatures]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,)"
    ordering = "NONE"
    side = "BOTH"