modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
    modId = "rottencreatures"
    version = "${version}"
    displayName = "Rotten Creatures"
    authors = "RPorotos, Team Fusion"
    description = '''
    Rotten Creatures is a mod that aims to add lots of fun new zombie variants to the game!
    '''
    logoFile = "icon.png"

[[dependencies.rottencreatures]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.rottencreatures]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,)"
    ordering = "NONE"
    side = "BOTH"